<a href="https://colab.research.google.com/github/Purushotham011/Neural-Networks-and-DL/blob/main/FNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

In [7]:
#Load and Prepare the Data
iris = load_iris()
x = iris.data
y = iris.target.reshape(-1,1)

encoder = OneHotEncoder(sparse_output=False)
y = encoder.fit_transform(y)

scaler = StandardScaler()
x = scaler.fit_transform(x)

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [8]:
#Fit data into the model
model =Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [25]:
#Train the Model
model.fit(x_train,y_train,epochs=100,batch_size=5)

Epoch 1/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9757 - loss: 0.0630     
Epoch 2/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9789 - loss: 0.0486     
Epoch 3/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9773 - loss: 0.0497 
Epoch 4/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9891 - loss: 0.0377 
Epoch 5/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9929 - loss: 0.0261     
Epoch 6/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9934 - loss: 0.0234     
Epoch 7/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9871 - loss: 0.0343 
Epoch 8/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9911 - loss: 0.0227     
Epoch 9/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9936 - loss: 0.0273     
Epoch 10/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9987 - loss: 0.0096     
Epoch 11/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9636 - loss: 0.0754     
Epoch 12/100
24/24 ━

In [23]:
#Evaluate the model
loss,accuracy = model.evaluate(x_test,y_test)
print(f'Loss:{loss},Accuracy:{accuracy}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0115
Loss:0.01149537693709135,Accuracy:1.0


In [17]:
#Make Predictions
predictions = model.predict(x_test)
print('Predictions : ')
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
Predictions : 
[[1.12213893e-05 9.98371482e-01 1.61724689e-03]
 [9.99991477e-01 8.49256048e-06 1.65965911e-18]
 [1.06618360e-12 7.94002858e-07 9.99999106e-01]
 [2.80398508e-05 9.81592178e-01 1.83796547e-02]
 [6.48282185e-06 9.85156834e-01 1.48366531e-02]
 [9.99978960e-01 2.09437312e-05 2.72340101e-17]
 [1.61455420e-04 9.99835730e-01 2.90583148e-06]
 [1.64174523e-07 2.01232685e-03 9.97987449e-01]
 [9.20670800e-07 6.51898444e-01 3.48100632e-01]
 [2.80707372e-05 9.99959528e-01 1.24548651e-05]
 [6.70119789e-06 6.12715296e-02 9.38721657e-01]
 [9.99997437e-01 2.50775520e-06 1.92032812e-18]
 [9.99996841e-01 3.13195778e-06 3.42980851e-19]
 [9.99997675e-01 2.27947339e-06 1.51948746e-18]
 [9.99999583e-01 4.08858568e-07 5.23291807e-20]
 [1.14929142e-04 9.86021280e-01 1.38637433e-02]
 [5.95725469e-09 1.30044864e-04 9.99870062e-01]
 [1.60882009e-05 9.99972999e-01 1.08762542e-05]
 [2.90372427e-05 9.98458683e-01 1.51219370e-03]
 [2.38814368e-09 9.59082317e-05 9.9